baseURL = 'https://alimoameri.github.io/'
languageCode = 'en-us'
title = "Ali Moameri's Blog"
theme = 'anubis2'


[params.author]
name = "Ali Moameri"

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Chroma style, find more at here: https://swapoff.org/chroma/playground/
